# Generated by Django 3.1.6 on 2021-02-08 17:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ctpo', '0003_auto_20210131_1533'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='training_programs',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='on_top',
            field=models.CharField(choices=[('top', 'На главную')], default='draft', max_length=10),
        ),
    ]
