# Generated by Django 3.1.5 on 2021-02-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctpo', '0004_auto_20210213_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_programs',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
