# Generated by Django 3.1.5 on 2021-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctpo', '0006_auto_20210214_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='on_main',
            field=models.CharField(choices=[('No', 'В базу'), ('Yes', 'На главную')], default='No', max_length=10, verbose_name='Позицианирование'),
        ),
        migrations.AddField(
            model_name='post',
            name='Превью изображение',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
