# Generated by Django 3.1.5 on 2021-02-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctpo', '0007_auto_20210214_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='on_main',
            field=models.CharField(choices=[('no', 'В базу'), ('yes', 'На главную')], default='No', max_length=10, verbose_name='Позицианирование'),
        ),
    ]
