# Generated by Django 3.1.5 on 2021-02-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctpo', '0009_auto_20210214_1951'),
        ('ctpo', '0004_auto_20210208_1713'),
    ]

    operations = [
    ]
