# Generated by Django 3.1.5 on 2021-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'В работе'), ('published', 'Опубликована')], default='draft', max_length=10),
        ),
    ]
