# Generated by Django 3.1.5 on 2021-01-31 15:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ctpo', '0002_auto_20210131_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
