# Generated by Django 3.1.5 on 2021-02-13 16:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ctpo', '0003_auto_20210131_1533'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='training_programs',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='training_programs',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/Training_programs', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='training_programs',
            name='body',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='training_programs',
            name='sub_title',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='training_programs',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
