# Generated by Django 3.1.5 on 2021-02-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctpo', '0008_auto_20210214_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Превью изображение',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью изображение'),
        ),
    ]
